services:
  postgres:
    image: postgres:17-alpine
    container_name: psgr
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dbnet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d mydata" ]
      interval: 5s
      timeout: 5s
      retries: 5

  letter:
    build: ./app
    image: letter-backend
    container_name: letters
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:1234@postgres:5432/mydata"
      SQLALCHEMY_ECHO: "False"
    ports:
      - "8000:4000"
    networks:
      - dbnet
    volumes:
      - ./app:/app:ro
    depends_on:
      postgres:
        condition: service_healthy

networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data:
